### PR TITLE
Update to v1.19.1

### PR DESCRIPTION
**Pull request by xmnlab**
supersede #12 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xmnlab** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
Hi @scopatz @conda-forge/help-c-cpp 

the CI for osx is raising this error:

```

  "_gumbo_destroy_output", referenced from:
      _fz_parse_xml_from_html5 in libmupdf.a(xml.o)
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_gumbo_parse_with_options", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
      _fz_parse_xml_from_html5 in libmupdf.a(xml.o)
  "_gumbo_normalized_tagname", referenced from:
make: *** [Makefile:294: build/release/muraster] Error 1
make: *** Waiting for unfinished jobs....
      _xml_from_gumbo in libmupdf.a(xml.o)
  "_gumbo_destroy_output", referenced from:
      _fz_parse_xml_from_html5 in libmupdf.a(xml.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

do you have any idea?

**Comment by xmnlab** [comment]
> Hi @scopatz @conda-forge/help-c-cpp
> 
> the CI for osx is raising this error:
> 
> ```
> 
>   "_gumbo_destroy_output", referenced from:
>       _fz_parse_xml_from_html5 in libmupdf.a(xml.o)
> ld: symbol(s) not found for architecture x86_64
> Undefined symbols for architecture x86_64:
>   "_gumbo_parse_with_options", referenced from:
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>       _fz_parse_xml_from_html5 in libmupdf.a(xml.o)
>   "_gumbo_normalized_tagname", referenced from:
> make: *** [Makefile:294: build/release/muraster] Error 1
> make: *** Waiting for unfinished jobs....
>       _xml_from_gumbo in libmupdf.a(xml.o)
>   "_gumbo_destroy_output", referenced from:
>       _fz_parse_xml_from_html5 in libmupdf.a(xml.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> do you have any idea?

updating the patch for osx did the tricky .. now I am trying to fix other issues. nope to have it ready by tomorrow

**Comment by xmnlab** [comment]
now osx build is raising this error: 

```
Error: Could not find libmupdf-third.dylib
```

but it doesn't make any sense because it should be there ... does anyone knows how to fix that?

**Comment by xmnlab** [comment]
in order to move forward for the maintenance of this package I am proposing to skip OSX build for now until we have someone to maintain that. I will open an issue for that.

**Comment by xmnlab** [comment]
@scopatz https://github.com/orgs/conda-forge/teams/help-c-cpp

this PR is ready for review. thanks!

**Comment by xmnlab** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
In the osx build I only see these files being installed:
```
2022-08-16T20:47:30.8560040Z install -d $PREFIX/include/mupdf
2022-08-16T20:47:30.8641430Z install -d $PREFIX/include/mupdf/fitz
2022-08-16T20:47:30.8708370Z install -d $PREFIX/include/mupdf/pdf
2022-08-16T20:47:30.8774700Z install -m 644 include/mupdf/*.h $PREFIX/include/mupdf
2022-08-16T20:47:30.8847460Z install -m 644 include/mupdf/fitz/*.h $PREFIX/include/mupdf/fitz
2022-08-16T20:47:30.9247780Z install -m 644 include/mupdf/pdf/*.h $PREFIX/include/mupdf/pdf
2022-08-16T20:47:30.9450700Z install -d $PREFIX/lib
2022-08-16T20:47:30.9517840Z install -m 644 build/release/libmupdf.dylib $PREFIX/lib
2022-08-16T20:47:31.0221180Z install -d $PREFIX/bin
2022-08-16T20:47:31.0268290Z install -m 755  build/release/mutool build/release/muraster build/release/mupdf-gl $PREFIX/bin
2022-08-16T20:47:31.0322760Z install -d $PREFIX/share/man/man1
2022-08-16T20:47:31.0363920Z install -m 644 docs/man/*.1 $PREFIX/share/man/man1
2022-08-16T20:47:31.0493590Z install -d $PREFIX/share/doc/mupdf
2022-08-16T20:47:31.0594840Z # install -d $PREFIX/share/doc/mupdf/examples
2022-08-16T20:47:31.0697260Z install -m 644 README COPYING CHANGES $PREFIX/share/doc/mupdf
2022-08-16T20:47:31.0796950Z # install -m 644 docs/*.html docs/*.css docs/*.png $PREFIX/share/doc/mupdf
2022-08-16T20:47:31.0850560Z # install -m 644 docs/examples/* $PREFIX/share/doc/mupdf/examples
```

So, I don't see `libmupdf-third.dylib` being installed here.

**Comment by xmnlab** [comment]
thanks @saraedum ! appreciate that. I am trying again to fix the patch for osx

**Comment by xmnlab** [comment]
@saraedum now it is working :) thanks for your input! appreciate that!
this PR is ready for review :)

**Comment by xmnlab** [comment]
This PR is sitting here for 14 days. @conda-forge/core, is there someone that can help me?

**Comment by dopplershift** [comment]
@xmnlab Can you add yourself as a maintainer in a separate PR [following the documented method](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list)? Someone from core can merge that and then you can merge this.

**Comment by xmnlab** [comment]
sure thing! thanks @dopplershift , I will work on that now

**Comment by xmnlab** [comment]
@dopplershift , done: https://github.com/conda-forge/mupdf-feedstock/pull/21

**Pull request merged**
