### PR TITLE
mupdf 1.21.1

### PR DESCRIPTION
**Pull request by tarrade**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

My first PR for such package.
There is no mupdf-1.21.1-source.tar.xz but mupdf-1.21.1-source.tar.lz instead. Hopefully this is supported as well.

### CODE REVIEW

**Comment by tarrade** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
Not sure if it is the case, but maybe the patch file also needs some changes: https://github.com/conda-forge/mupdf-feedstock/blob/main/recipe/Makefile-shared-libs-osx.patch

**Comment by tarrade** [comment]
> Not sure if it is the case, but maybe the patch file also needs some changes: https://github.com/conda-forge/mupdf-feedstock/blob/main/recipe/Makefile-shared-libs-osx.patch

Thanks, I will look at that

**Comment by tarrade** [comment]
ok so in the makefile for 1.19.1 something was replace starting line 232 (if I understood well, never use patch)
@@ -232,46 +232,27 @@

now the same block start at line 270 but no idea what ,46 and , 27 means here. I will try something very naive

**Comment by tarrade** [comment]
@xmnlab maybe you can quickly review my changes in [Makefile-shared-libs-osx.patch](https://github.com/conda-forge/mupdf-feedstock/pull/23/commits/4fae558917a82952ee19ea0ab2b52f5e6caf2add) ? I had to do few changes:

- change start of block number 2 and 3
- replace a line in block 2
- add a line in block 3

I never work with patch. I downloaded the Makefile for version 1.19.1 and 1.21.1 and then look at previous version of Makefile-shared-libs-osx.patch to try to understand how this work.

It seems that it works for OSX

**Comment by xmnlab** [comment]
LGTM! Thanks for working on that @tarrade !

**Pull request merged**
